In [24]:
import os

print(os.getcwd())
print(os.listdir())

c:\Users\Admin\OneDrive\Desktop\OASIS INFOBYTE\task 2 dirty dataset
['cleaned_tour_data.csv', 'dirty data set.ipynb', 'my_file (1).csv']

In [25]:
import pandas as pd

df = pd.read_csv('my_file (1).csv')
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [26]:
# Check dataset size
print("Dataset Shape:", df.shape)

# Check column names
print("\nColumns:")
print(df.columns.tolist())

# Check data types
print("\nData Types:")
print(df.dtypes)

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Check duplicate rows
print("\nDuplicate Rows:", df.duplicated().sum())

Dataset Shape: (20, 11)

Columns:
['Rank', 'Peak', 'All Time Peak', 'Actual\xa0gross', 'Adjusted\xa0gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)', 'Shows', 'Average gross', 'Ref.']

Data Types:
Rank                                int64
Peak                                  str
All Time Peak                         str
Actual gross                          str
Adjusted gross (in 2022 dollars)      str
Artist                                str
Tour title                            str
Year(s)                               str
Shows                               int64
Average gross                         str
Ref.                                  str
dtype: object

Missing Values:
Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

Duplicate Rows: 0

In [27]:
# Save BEFORE-cleaning information
before_rows = len(df)
before_nulls = df.isnull().sum().sum()
before_duplicates = df.duplicated().sum()
before_dtypes = df.dtypes.astype(str)

print("Rows:", before_rows)
print("Total Null Values:", before_nulls)
print("Duplicate Rows:", before_duplicates)

print("\nMissing Values Per Column:")
print(df.isnull().sum())

print("\nData Types:")
print(df.dtypes)

Rows: 20
Total Null Values: 25
Duplicate Rows: 0

Missing Values Per Column:
Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

Data Types:
Rank                                int64
Peak                                  str
All Time Peak                         str
Actual gross                          str
Adjusted gross (in 2022 dollars)      str
Artist                                str
Tour title                            str
Year(s)                               str
Shows                               int64
Average gross                         str
Ref.                                  str
dtype: object

In [28]:
# Clean column names
df.columns = (
    df.columns
      .str.replace('\xa0', ' ', regex=False)
      .str.strip()
)

print(df.columns.tolist())

['Rank', 'Peak', 'All Time Peak', 'Actual gross', 'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)', 'Shows', 'Average gross', 'Ref.']

In [29]:
df.head(10)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]

In [30]:
for column in df.columns:
    print(f"\n--- {column} ---")
    print(df[column].head(10).tolist())

--- Rank ---
[1, 2, 3, 4, 5, 6, 7, 7, 9, 10]

--- Peak ---
['1', '1', '1[4]', '2[7]', '2[4]', '2[4]', '2[10]', nan, nan, nan]

--- All Time Peak ---
['2', '7[2]', '2[5]', '10[7]', nan, '10[9]', nan, nan, nan, nan]

--- Actual gross ---
['$780,000,000', '$579,800,000', '$411,000,000', '$397,300,000', '$345,675,146', '$305,158,363', '$280,000,000', '$257,600,000', '$256,084,556', '$250,400,000']

--- Adjusted gross (in 2022 dollars) ---
['$780,000,000', '$579,800,000', '$560,622,615', '$454,751,555', '$402,844,849', '$388,978,496', '$381,932,682', '$257,600,000', '$312,258,401', '$309,141,878']

--- Artist ---
['Taylor Swift', 'Beyoncé', 'Madonna', 'Pink', 'Taylor Swift', 'Madonna', 'Celine Dion', 'Pink', 'Beyoncé', 'Taylor Swift']

--- Tour title ---
['The Eras Tour †', 'Renaissance World Tour', 'Sticky & Sweet Tour ‡[4][a]', 'Beautiful Trauma World Tour', 'Reputation Stadium Tour', 'The MDNA Tour', 'Taking Chances World Tour', 'Summer Carnival †', 'The Formation World Tour', 'The 1989 World Tour']

--- Year(s) ---
['2023–2024', '2023', '2008–2009', '2018–2019', '2018', '2012', '2008–2009', '2023–2024', '2016', '2015']

--- Shows ---
[56, 56, 85, 156, 53, 88, 131, 41, 49, 85]

--- Average gross ---
['$13,928,571', '$10,353,571', '$4,835,294', '$2,546,795', '$6,522,173', '$3,467,709', '$2,137,405', '$6,282,927', '$5,226,215', '$2,945,882']

--- Ref. ---
['[1]', '[3]', '[6]', '[7]', '[8]', '[9]', '[11]', '[12]', '[13]', '[14]']

In [31]:
print(df.isnull().sum())

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [32]:
# Clean ranking values and handle missing values
for col in ['Peak', 'All Time Peak']:
    # Extract the actual rank from values such as "1[4]" or "2[7]"
    df[col] = pd.to_numeric(
        df[col].astype('string').str.extract(r'(\d+)')[0],
        errors='coerce'
    )

    # Fill missing rankings with the most common rank
    df[col] = df[col].fillna(df[col].mode().iloc[0])

print(df.isnull().sum())

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

## Missing Data Handling

Missing values were found only in the Peak and all time peak columns. Since these columns represent discrete ranking values, the missing values were filled using the mode rather than the mean. This preserves realistic ranking values without removing rows from the dataset.

In [33]:
# Check and remove duplicate rows
duplicates_before = df.duplicated().sum()

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicates before:", duplicates_before)
print("Duplicates after:", duplicates_after)

Duplicates before: 0
Duplicates after: 0

## Duplicate Removal

Duplicate rows were checked and removed to prevent repeated records from affecting the analysis. The number of duplicates before and after cleaning was documented.

In [34]:
# Clean text columns
text_columns = ['Artist', 'Tour title', 'Year(s)', 'Ref.']

for col in text_columns:
    df[col] = df[col].astype('string').str.strip()

# Remove citation symbols/references from tour titles
df['Tour title'] = (
    df['Tour title']
    .str.replace(r'\[[^\]]+\]', '', regex=True)
    .str.replace('†', '', regex=False)
    .str.replace('‡', '', regex=False)
    .str.strip()
)

# Clean monetary columns
money_columns = [
    'Actual gross',
    'Adjusted gross (in 2022 dollars)',
    'Average gross'
]

for col in money_columns:
    df[col] = (
        df[col]
        .astype('string')
        .str.replace('$', '', regex=False)
        .str.replace(',', '', regex=False)
    )

    df[col] = pd.to_numeric(df[col], errors='coerce')

df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour,2023–2024,56,13928571,[1]
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour,2008–2009,85,4835294,[6]
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7]
4,5,2,2,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]

## Data Standardisation

Text values were stripped of unnecessary spaces and tour titles were cleaned by removing reference symbols and citation markers. Monetary columns were standardised by removing dollar signs and commas so they could be converted into numerical values.

In [35]:
print(df.dtypes)
print(df.isnull().sum())

Rank                                 int64
Peak                                 Int64
All Time Peak                        Int64
Actual gross                         Int64
Adjusted gross (in 2022 dollars)     Int64
Artist                              string
Tour title                          string
Year(s)                             string
Shows                                int64
Average gross                        Int64
Ref.                                string
dtype: object
Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        2
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

In [36]:
# Fill missing Actual gross values using Shows × Average gross
df['Actual gross'] = df['Actual gross'].fillna(
    df['Shows'] * df['Average gross']
)

print(df.isnull().sum())

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

### Additional Missing Value Handling

Two values in Actual gross became missing during numeric conversion because of inconsistent formatting. They were reconstructed using the number of shows multiplied by the average gross per show, preserving the relationship between the existing variables.

In [37]:
numeric_columns = [
    'Actual gross',
    'Adjusted gross (in 2022 dollars)',
    'Shows',
    'Average gross'
]

for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(f"{col}: {len(outliers)} outliers")

Actual gross: 2 outliers
Adjusted gross (in 2022 dollars): 1 outliers
Shows: 1 outliers
Average gross: 2 outliers

## Outlier Detection

The IQR method identified 2 outliers in Actual gross, 1 in Adjusted gross (in 2022 dollars), 1 in Shows, and 2 in Average gross.

These outliers were retained because extremely successful tours can legitimately generate much higher revenue or have more shows than typical tours. Removing them could eliminate meaningful real-world observations.

In [38]:
# Correct data types

df['Rank'] = df['Rank'].astype('int64')
df['Peak'] = df['Peak'].astype('int64')
df['All Time Peak'] = df['All Time Peak'].astype('int64')

df['Actual gross'] = df['Actual gross'].astype(float)
df['Adjusted gross (in 2022 dollars)'] = df['Adjusted gross (in 2022 dollars)'].astype(float)
df['Average gross'] = df['Average gross'].astype(float)

df['Shows'] = df['Shows'].astype('int64')

df['Artist'] = df['Artist'].astype('string')
df['Tour title'] = df['Tour title'].astype('string')
df['Year(s)'] = df['Year(s)'].astype('string')
df['Ref.'] = df['Ref.'].astype('string')

print(df.dtypes)

Rank                                  int64
Peak                                  int64
All Time Peak                         int64
Actual gross                        float64
Adjusted gross (in 2022 dollars)    float64
Artist                               string
Tour title                           string
Year(s)                              string
Shows                                 int64
Average gross                       float64
Ref.                                 string
dtype: object

## Data Type Correction

Ranking and show-count columns were converted to integer types, monetary columns were converted to float, and descriptive text columns were stored as strings. This ensures that each variable has an appropriate data type for analysis.

In [39]:
# BEFORE vs AFTER summary

after_rows = len(df)
after_nulls = df.isnull().sum().sum()
after_duplicates = df.duplicated().sum()

summary = pd.DataFrame({
    'Metric': ['Row Count', 'Null Values', 'Duplicate Rows'],
    'Before': [before_rows, before_nulls, before_duplicates],
    'After': [after_rows, after_nulls, after_duplicates]
})

summary

           Metric  Before  After
0       Row Count      20     20
1     Null Values      25      0
2  Duplicate Rows       0      0

In [40]:
df.to_csv('cleaned_tour_data.csv', index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

## Cleaning Summary

The dataset was cleaned by handling missing values, removing duplicates, standardising text and monetary values, detecting and retaining valid outliers, and correcting data types. A cleaned version of the dataset was then saved as a new CSV file.